# Generated by Django 6.0.1 on 2026-01-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[("RENT", "Rental"), ("SALE", "Sale")],
                        default="RENT",
                        max_length=4,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price per day (Rent) or Full Price (Sale)",
                        max_digits=10,
                    ),
                ),
                ("image", models.ImageField(upload_to="cars/")),
                (
                    "specs",
                    models.TextField(
                        help_text="JSON or simple text. e.g., '0-100: 3.5s, Engine: V8'"
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
